# Generated by Django 3.0.4 on 2020-06-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('category', models.CharField(default='', max_length=50)),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head0', models.TextField(default='', max_length=500)),
                ('chead0', models.TextField(default='', max_length=5000)),
                ('head1', models.TextField(default='', max_length=500)),
                ('chead1', models.TextField(default='', max_length=5000)),
                ('head2', models.TextField(default='', max_length=500)),
                ('chead2', models.TextField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='webapp/images')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
