const express = require('express');
const open = require('open');
const http = require('http');
const app = express();
const port = 7777;
app.use(express.static(__dirname + '/dist/lp3-assignment'));
app.get('/api/datetime', (req, res) => res.send(Date()));
const server = http.createServer(app);
server.listen(port, () => console.log("Server started on port " + port + "\nOpening http://localhost:7777/ on default browser."));
open('http://localhost:7777/');